################################################################################
# Development set-up for the website using Docker.                             #
################################################################################
name: website

# Common build configuration for all the targets built from docker/website/Dockerfile.
x-build-dockerfile: &build-dockerfile
  context: .
  dockerfile: docker/website/Dockerfile
  args:
    NGINX_VERSION: $NGINX_VERSION
    NGINX_ALPINE_VERSION: $NGINX_ALPINE_VERSION
    PHP_VERSION: $PHP_VERSION
    PHP_ALPINE_VERSION: $PHP_ALPINE_VERSION
    COMPOSER_VERSION: $COMPOSER_VERSION
  platforms:
    - linux/amd64
    - linux/arm64

services:
  router:
    build:
      <<: *build-dockerfile
      target: router-development
    env_file:
      - .env.development
    volumes_from:
      - website:ro
    networks:
      default:
        aliases:
          - ${WEBSITE_ROUTER_ALIAS:-cablecar.localhost.getopensocial.net}
    ports:
      - "80:80"
    tmpfs:
      - /tmp

  website:
    build:
      <<: *build-dockerfile
      target: php-fpm-development
    env_file:
      - .env.development
    depends_on:
      - database
    volumes:
      - .:/app/:delegated
      - ./docker/website/settings.docker.php:/app/html/sites/default/settings.docker.php:ro
      - ./docker/website/php-fpm-development.ini:/usr/local/etc/php/conf.d/website-php.ini:ro

  cli:
    profiles:
      - cli
    build:
      <<: *build-dockerfile
      target: php-cli-development
    env_file:
      - .env.development
    depends_on:
      - database
    volumes:
      - .:/app/:delegated
      - ./docker/website/settings.docker.php:/app/html/sites/default/settings.docker.php:ro
      - ./docker/website/php-fpm-development.ini:/usr/local/etc/php/conf.d/website-php.ini:ro

  database:
    image: mariadb:${MARIADB_VERSION}
    command: mysqld --max_allowed_packet=16M
    env_file:
      - .env.development
    volumes:
      - database:/var/lib/mysql
    ports:
      - "3306"

volumes:
  database:
